steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull',
           'gcr.io/$PROJECT_ID/$REPO_NAME:$_SOURCE_TAG']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/bash
    args:
      - -c
      - docker images --format "{{.Digest}}" > /workspace/sourceDigest

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        gcloud beta run deploy $_SERVICE_NAME \
           --image "gcr.io/$PROJECT_ID/$REPO_NAME:`echo /workspace/sourceDigest`" \
           --region $_REGION \
           --platform $_PLATFORM \
           --set-env-vars "GCP_PROJECT=$PROJECT_ID,LOG_ID_ENV=PROD" \
           --quiet

  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag',
           'gcr.io/$PROJECT_ID/$REPO_NAME:$_SOURCE_TAG',
           'gcr.io/$PROJECT_ID/$REPO_NAME:$_DEST_TAG']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'gcr.io/$PROJECT_ID/$REPO_NAME:$_DEST_TAG']

substitutions:
  _SOURCE_TAG: staging
  _DEST_TAG: prod
  _SERVICE_NAME: stats-prod-us-central1
  _REGION: us-central1
  _PLATFORM: managed
