steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA',
         '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
         '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:staging',
         '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run',
         'deploy', '$_SERVICE_NAME',
         '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA',
         '--region', '$_REGION',
         '--platform', '$_PLATFORM',
         '--set-env-vars', 'GCP_PROJECT=$PROJECT_ID',
         '--quiet']

substitutions:
  _SERVICE_NAME: stats-staging
  _REGION: us-central1
  _PLATFORM: managed

images:
- gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
- gcr.io/$PROJECT_ID/$REPO_NAME:latest
- gcr.io/$PROJECT_ID/$REPO_NAME:staging
