// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package stats

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Sourced from https://github.com/spinnaker/orca/blob/master/orca-core/src/main/java/com/netflix/spinnaker/orca/ExecutionStatus.java
type Status int32

const (
	Status_UNKNOWN         Status = 0
	Status_NOT_STARTED     Status = 1
	Status_RUNNING         Status = 2
	Status_PAUSED          Status = 3
	Status_SUSPENDED       Status = 4
	Status_SUCCEEDED       Status = 5
	Status_FAILED_CONTINUE Status = 6
	Status_TERMINAL        Status = 7
	Status_CANCELED        Status = 8
	Status_REDIRECT        Status = 9
	Status_STOPPED         Status = 10
	Status_SKIPPED         Status = 11
	Status_BUFFERED        Status = 12
)

var Status_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "NOT_STARTED",
	2:  "RUNNING",
	3:  "PAUSED",
	4:  "SUSPENDED",
	5:  "SUCCEEDED",
	6:  "FAILED_CONTINUE",
	7:  "TERMINAL",
	8:  "CANCELED",
	9:  "REDIRECT",
	10: "STOPPED",
	11: "SKIPPED",
	12: "BUFFERED",
}

var Status_value = map[string]int32{
	"UNKNOWN":         0,
	"NOT_STARTED":     1,
	"RUNNING":         2,
	"PAUSED":          3,
	"SUSPENDED":       4,
	"SUCCEEDED":       5,
	"FAILED_CONTINUE": 6,
	"TERMINAL":        7,
	"CANCELED":        8,
	"REDIRECT":        9,
	"STOPPED":         10,
	"SKIPPED":         11,
	"BUFFERED":        12,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}

type Execution_Type int32

const (
	Execution_UNKNOWN                      Execution_Type = 0
	Execution_PIPELINE                     Execution_Type = 1
	Execution_ORCHESTRATION                Execution_Type = 2
	Execution_MANAGED_PIPELINE_TEMPLATE_V1 Execution_Type = 3
	Execution_MANAGED_PIPELINE_TEMPLATE_V2 Execution_Type = 4
)

var Execution_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "PIPELINE",
	2: "ORCHESTRATION",
	3: "MANAGED_PIPELINE_TEMPLATE_V1",
	4: "MANAGED_PIPELINE_TEMPLATE_V2",
}

var Execution_Type_value = map[string]int32{
	"UNKNOWN":                      0,
	"PIPELINE":                     1,
	"ORCHESTRATION":                2,
	"MANAGED_PIPELINE_TEMPLATE_V1": 3,
	"MANAGED_PIPELINE_TEMPLATE_V2": 4,
}

func (x Execution_Type) String() string {
	return proto.EnumName(Execution_Type_name, int32(x))
}

func (Execution_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{3, 0}
}

// Sourced from https://github.com/spinnaker/echo/tree/master/echo-model/src/main/java/com/netflix/spinnaker/echo/model/trigger
type Execution_Trigger_Type int32

const (
	Execution_Trigger_UNKNOWN     Execution_Trigger_Type = 0
	Execution_Trigger_ARTIFACTORY Execution_Trigger_Type = 1
	Execution_Trigger_BUILD       Execution_Trigger_Type = 2
	Execution_Trigger_DOCKER      Execution_Trigger_Type = 3
	Execution_Trigger_GIT         Execution_Trigger_Type = 4
	Execution_Trigger_MANUAL      Execution_Trigger_Type = 5
	Execution_Trigger_PUBSUB      Execution_Trigger_Type = 6
	Execution_Trigger_WEBHOOK     Execution_Trigger_Type = 7
)

var Execution_Trigger_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "ARTIFACTORY",
	2: "BUILD",
	3: "DOCKER",
	4: "GIT",
	5: "MANUAL",
	6: "PUBSUB",
	7: "WEBHOOK",
}

var Execution_Trigger_Type_value = map[string]int32{
	"UNKNOWN":     0,
	"ARTIFACTORY": 1,
	"BUILD":       2,
	"DOCKER":      3,
	"GIT":         4,
	"MANUAL":      5,
	"PUBSUB":      6,
	"WEBHOOK":     7,
}

func (x Execution_Trigger_Type) String() string {
	return proto.EnumName(Execution_Trigger_Type_name, int32(x))
}

func (Execution_Trigger_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{3, 0, 0}
}

type CloudProvider_ID int32

const (
	CloudProvider_UNKNOWN      CloudProvider_ID = 0
	CloudProvider_APPENGINE    CloudProvider_ID = 1
	CloudProvider_AWS          CloudProvider_ID = 2
	CloudProvider_AZURE        CloudProvider_ID = 3
	CloudProvider_CLOUDFOUNDRY CloudProvider_ID = 4
	CloudProvider_DCOS         CloudProvider_ID = 5
	CloudProvider_ECS          CloudProvider_ID = 6
	CloudProvider_GCE          CloudProvider_ID = 7
	CloudProvider_KUBERNETES   CloudProvider_ID = 8
	CloudProvider_ORACLE       CloudProvider_ID = 9
)

var CloudProvider_ID_name = map[int32]string{
	0: "UNKNOWN",
	1: "APPENGINE",
	2: "AWS",
	3: "AZURE",
	4: "CLOUDFOUNDRY",
	5: "DCOS",
	6: "ECS",
	7: "GCE",
	8: "KUBERNETES",
	9: "ORACLE",
}

var CloudProvider_ID_value = map[string]int32{
	"UNKNOWN":      0,
	"APPENGINE":    1,
	"AWS":          2,
	"AZURE":        3,
	"CLOUDFOUNDRY": 4,
	"DCOS":         5,
	"ECS":          6,
	"GCE":          7,
	"KUBERNETES":   8,
	"ORACLE":       9,
}

func (x CloudProvider_ID) String() string {
	return proto.EnumName(CloudProvider_ID_name, int32(x))
}

func (CloudProvider_ID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{5, 0}
}

type Event struct {
	SpinnakerInstance    *SpinnakerInstance `protobuf:"bytes,1,opt,name=spinnaker_instance,json=spinnakerInstance,proto3" json:"spinnaker_instance,omitempty"`
	Application          *Application       `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	Execution            *Execution         `protobuf:"bytes,3,opt,name=execution,proto3" json:"execution,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetSpinnakerInstance() *SpinnakerInstance {
	if m != nil {
		return m.SpinnakerInstance
	}
	return nil
}

func (m *Event) GetApplication() *Application {
	if m != nil {
		return m.Application
	}
	return nil
}

func (m *Event) GetExecution() *Execution {
	if m != nil {
		return m.Execution
	}
	return nil
}

type SpinnakerInstance struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpinnakerInstance) Reset()         { *m = SpinnakerInstance{} }
func (m *SpinnakerInstance) String() string { return proto.CompactTextString(m) }
func (*SpinnakerInstance) ProtoMessage()    {}
func (*SpinnakerInstance) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{1}
}

func (m *SpinnakerInstance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpinnakerInstance.Unmarshal(m, b)
}
func (m *SpinnakerInstance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpinnakerInstance.Marshal(b, m, deterministic)
}
func (m *SpinnakerInstance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpinnakerInstance.Merge(m, src)
}
func (m *SpinnakerInstance) XXX_Size() int {
	return xxx_messageInfo_SpinnakerInstance.Size(m)
}
func (m *SpinnakerInstance) XXX_DiscardUnknown() {
	xxx_messageInfo_SpinnakerInstance.DiscardUnknown(m)
}

var xxx_messageInfo_SpinnakerInstance proto.InternalMessageInfo

func (m *SpinnakerInstance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SpinnakerInstance) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Application struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{2}
}

func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Execution struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 Execution_Type     `protobuf:"varint,2,opt,name=type,proto3,enum=io.spinnaker.proto.stats.Execution_Type" json:"type,omitempty"`
	Trigger              *Execution_Trigger `protobuf:"bytes,3,opt,name=trigger,proto3" json:"trigger,omitempty"`
	Stages               []*Stage           `protobuf:"bytes,4,rep,name=stages,proto3" json:"stages,omitempty"`
	Status               Status             `protobuf:"varint,5,opt,name=status,proto3,enum=io.spinnaker.proto.stats.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Execution) Reset()         { *m = Execution{} }
func (m *Execution) String() string { return proto.CompactTextString(m) }
func (*Execution) ProtoMessage()    {}
func (*Execution) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{3}
}

func (m *Execution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Execution.Unmarshal(m, b)
}
func (m *Execution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Execution.Marshal(b, m, deterministic)
}
func (m *Execution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Execution.Merge(m, src)
}
func (m *Execution) XXX_Size() int {
	return xxx_messageInfo_Execution.Size(m)
}
func (m *Execution) XXX_DiscardUnknown() {
	xxx_messageInfo_Execution.DiscardUnknown(m)
}

var xxx_messageInfo_Execution proto.InternalMessageInfo

func (m *Execution) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Execution) GetType() Execution_Type {
	if m != nil {
		return m.Type
	}
	return Execution_UNKNOWN
}

func (m *Execution) GetTrigger() *Execution_Trigger {
	if m != nil {
		return m.Trigger
	}
	return nil
}

func (m *Execution) GetStages() []*Stage {
	if m != nil {
		return m.Stages
	}
	return nil
}

func (m *Execution) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNKNOWN
}

type Execution_Trigger struct {
	Type                 Execution_Trigger_Type `protobuf:"varint,1,opt,name=type,proto3,enum=io.spinnaker.proto.stats.Execution_Trigger_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Execution_Trigger) Reset()         { *m = Execution_Trigger{} }
func (m *Execution_Trigger) String() string { return proto.CompactTextString(m) }
func (*Execution_Trigger) ProtoMessage()    {}
func (*Execution_Trigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{3, 0}
}

func (m *Execution_Trigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Execution_Trigger.Unmarshal(m, b)
}
func (m *Execution_Trigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Execution_Trigger.Marshal(b, m, deterministic)
}
func (m *Execution_Trigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Execution_Trigger.Merge(m, src)
}
func (m *Execution_Trigger) XXX_Size() int {
	return xxx_messageInfo_Execution_Trigger.Size(m)
}
func (m *Execution_Trigger) XXX_DiscardUnknown() {
	xxx_messageInfo_Execution_Trigger.DiscardUnknown(m)
}

var xxx_messageInfo_Execution_Trigger proto.InternalMessageInfo

func (m *Execution_Trigger) GetType() Execution_Trigger_Type {
	if m != nil {
		return m.Type
	}
	return Execution_Trigger_UNKNOWN
}

type Stage struct {
	Type                 string         `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status               Status         `protobuf:"varint,2,opt,name=status,proto3,enum=io.spinnaker.proto.stats.Status" json:"status,omitempty"`
	CloudProvider        *CloudProvider `protobuf:"bytes,3,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Stage) Reset()         { *m = Stage{} }
func (m *Stage) String() string { return proto.CompactTextString(m) }
func (*Stage) ProtoMessage()    {}
func (*Stage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{4}
}

func (m *Stage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stage.Unmarshal(m, b)
}
func (m *Stage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stage.Marshal(b, m, deterministic)
}
func (m *Stage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stage.Merge(m, src)
}
func (m *Stage) XXX_Size() int {
	return xxx_messageInfo_Stage.Size(m)
}
func (m *Stage) XXX_DiscardUnknown() {
	xxx_messageInfo_Stage.DiscardUnknown(m)
}

var xxx_messageInfo_Stage proto.InternalMessageInfo

func (m *Stage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Stage) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNKNOWN
}

func (m *Stage) GetCloudProvider() *CloudProvider {
	if m != nil {
		return m.CloudProvider
	}
	return nil
}

type CloudProvider struct {
	Id                   CloudProvider_ID `protobuf:"varint,1,opt,name=id,proto3,enum=io.spinnaker.proto.stats.CloudProvider_ID" json:"id,omitempty"`
	Variant              string           `protobuf:"bytes,2,opt,name=variant,proto3" json:"variant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CloudProvider) Reset()         { *m = CloudProvider{} }
func (m *CloudProvider) String() string { return proto.CompactTextString(m) }
func (*CloudProvider) ProtoMessage()    {}
func (*CloudProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{5}
}

func (m *CloudProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudProvider.Unmarshal(m, b)
}
func (m *CloudProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudProvider.Marshal(b, m, deterministic)
}
func (m *CloudProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudProvider.Merge(m, src)
}
func (m *CloudProvider) XXX_Size() int {
	return xxx_messageInfo_CloudProvider.Size(m)
}
func (m *CloudProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudProvider.DiscardUnknown(m)
}

var xxx_messageInfo_CloudProvider proto.InternalMessageInfo

func (m *CloudProvider) GetId() CloudProvider_ID {
	if m != nil {
		return m.Id
	}
	return CloudProvider_UNKNOWN
}

func (m *CloudProvider) GetVariant() string {
	if m != nil {
		return m.Variant
	}
	return ""
}

func init() {
	proto.RegisterEnum("io.spinnaker.proto.stats.Status", Status_name, Status_value)
	proto.RegisterEnum("io.spinnaker.proto.stats.Execution_Type", Execution_Type_name, Execution_Type_value)
	proto.RegisterEnum("io.spinnaker.proto.stats.Execution_Trigger_Type", Execution_Trigger_Type_name, Execution_Trigger_Type_value)
	proto.RegisterEnum("io.spinnaker.proto.stats.CloudProvider_ID", CloudProvider_ID_name, CloudProvider_ID_value)
	proto.RegisterType((*Event)(nil), "io.spinnaker.proto.stats.Event")
	proto.RegisterType((*SpinnakerInstance)(nil), "io.spinnaker.proto.stats.SpinnakerInstance")
	proto.RegisterType((*Application)(nil), "io.spinnaker.proto.stats.Application")
	proto.RegisterType((*Execution)(nil), "io.spinnaker.proto.stats.Execution")
	proto.RegisterType((*Execution_Trigger)(nil), "io.spinnaker.proto.stats.Execution.Trigger")
	proto.RegisterType((*Stage)(nil), "io.spinnaker.proto.stats.Stage")
	proto.RegisterType((*CloudProvider)(nil), "io.spinnaker.proto.stats.CloudProvider")
}

func init() { proto.RegisterFile("log.proto", fileDescriptor_a153da538f858886) }

var fileDescriptor_a153da538f858886 = []byte{
	// 798 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4f, 0x6f, 0xe3, 0x44,
	0x1c, 0xc5, 0x89, 0x13, 0xd7, 0xbf, 0xb4, 0xd9, 0xe9, 0x70, 0x89, 0x10, 0x88, 0xca, 0x08, 0xa8,
	0x76, 0x85, 0xbb, 0x84, 0x03, 0x08, 0xc1, 0x61, 0xe2, 0xf9, 0x25, 0x6b, 0xc5, 0x1d, 0x5b, 0x63,
	0x9b, 0x6a, 0x2b, 0xa4, 0x28, 0x9b, 0x9a, 0x60, 0xb5, 0x1b, 0x47, 0xb1, 0x53, 0x75, 0x2f, 0x7c,
	0x1b, 0xbe, 0x04, 0x67, 0x4e, 0x7c, 0x0f, 0xce, 0x7c, 0x05, 0x34, 0x93, 0x3f, 0xcd, 0x6e, 0xe9,
	0xd2, 0x5e, 0xac, 0xbc, 0xc9, 0x7b, 0x6f, 0x7e, 0x33, 0xef, 0x0d, 0xd8, 0x57, 0xc5, 0xd4, 0x9d,
	0x2f, 0x8a, 0xaa, 0xa0, 0x9d, 0xbc, 0x70, 0xcb, 0x79, 0x3e, 0x9b, 0x8d, 0x2f, 0xb3, 0xc5, 0x6a,
	0xcd, 0x2d, 0xab, 0x71, 0x55, 0x3a, 0xff, 0x18, 0xd0, 0xc0, 0xeb, 0x6c, 0x56, 0xd1, 0x73, 0xa0,
	0x5b, 0xca, 0x28, 0x9f, 0x95, 0xd5, 0x78, 0x36, 0xc9, 0x3a, 0xc6, 0x91, 0x71, 0xdc, 0xea, 0x3e,
	0x73, 0xef, 0x33, 0x70, 0xe3, 0xcd, 0xaa, 0xbf, 0x96, 0xc8, 0xc3, 0xf2, 0xdd, 0x25, 0x3a, 0x80,
	0xd6, 0x78, 0x3e, 0xbf, 0xca, 0x27, 0xe3, 0x2a, 0x2f, 0x66, 0x9d, 0x9a, 0x36, 0xfd, 0xfc, 0x7e,
	0x53, 0x76, 0x4b, 0x96, 0xbb, 0x4a, 0xca, 0xc0, 0xce, 0x6e, 0xb2, 0xc9, 0x52, 0xdb, 0xd4, 0xb5,
	0xcd, 0x67, 0xf7, 0xdb, 0xe0, 0x86, 0x2a, 0x6f, 0x55, 0xce, 0x8f, 0x70, 0x78, 0x67, 0x66, 0xda,
	0x86, 0x5a, 0x7e, 0xa1, 0x0f, 0x6b, 0xcb, 0x5a, 0x7e, 0x41, 0x3b, 0x60, 0x5d, 0x67, 0x8b, 0x72,
	0x33, 0xac, 0x2d, 0x37, 0xd0, 0xf9, 0x04, 0x5a, 0x3b, 0xd3, 0xbd, 0x2b, 0x74, 0xfe, 0x32, 0xc1,
	0xde, 0x6e, 0x7b, 0xc7, 0xf6, 0x07, 0x30, 0xab, 0x37, 0xf3, 0x4c, 0x7b, 0xb6, 0xbb, 0xc7, 0x0f,
	0x98, 0xdc, 0x4d, 0xde, 0xcc, 0x33, 0xa9, 0x55, 0x14, 0xc1, 0xaa, 0x16, 0xf9, 0x74, 0x9a, 0x2d,
	0xd6, 0x47, 0x7f, 0xf6, 0x20, 0x83, 0x95, 0x44, 0x6e, 0xb4, 0xf4, 0x5b, 0x68, 0x96, 0xd5, 0x78,
	0x9a, 0x95, 0x1d, 0xf3, 0xa8, 0x7e, 0xdc, 0xea, 0x7e, 0xfa, 0x9e, 0x70, 0x15, 0x4f, 0xae, 0xe9,
	0xf4, 0x3b, 0x2d, 0xac, 0x96, 0x65, 0xa7, 0xa1, 0xe7, 0x3f, 0x7a, 0xaf, 0xb0, 0x5a, 0x96, 0x72,
	0xcd, 0xff, 0xe8, 0x0f, 0x03, 0xac, 0xf5, 0x1c, 0x94, 0xaf, 0xef, 0xc0, 0xd0, 0x1e, 0xcf, 0x1f,
	0x71, 0x84, 0x9d, 0xbb, 0x70, 0x72, 0x30, 0x15, 0xa2, 0x2d, 0xb0, 0x52, 0x31, 0x14, 0xe1, 0x99,
	0x20, 0x1f, 0xd0, 0x27, 0xd0, 0x62, 0x32, 0xf1, 0xfb, 0xcc, 0x4b, 0x42, 0xf9, 0x92, 0x18, 0xd4,
	0x86, 0x46, 0x2f, 0xf5, 0x03, 0x4e, 0x6a, 0x14, 0xa0, 0xc9, 0x43, 0x6f, 0x88, 0x92, 0xd4, 0xa9,
	0x05, 0xf5, 0x81, 0x9f, 0x10, 0x53, 0x2d, 0x9e, 0x32, 0x91, 0xb2, 0x80, 0x34, 0xd4, 0xef, 0x28,
	0xed, 0xc5, 0x69, 0x8f, 0x34, 0x95, 0xeb, 0x19, 0xf6, 0x5e, 0x84, 0xe1, 0x90, 0x58, 0xce, 0xcd,
	0x7f, 0x6d, 0xb5, 0x0f, 0x7b, 0x91, 0x1f, 0x61, 0xe0, 0x0b, 0x24, 0x06, 0x3d, 0x84, 0x83, 0x50,
	0x7a, 0x2f, 0x30, 0x4e, 0x24, 0x4b, 0xfc, 0x50, 0x90, 0x1a, 0x3d, 0x82, 0x8f, 0x4f, 0x99, 0x60,
	0x03, 0xe4, 0xa3, 0x0d, 0x71, 0x94, 0xe0, 0x69, 0x14, 0xb0, 0x04, 0x47, 0x3f, 0x7d, 0x4d, 0xea,
	0xff, 0xc3, 0xe8, 0x12, 0xd3, 0xf9, 0xdd, 0x80, 0x86, 0x8e, 0x80, 0xd2, 0x9d, 0x4b, 0xb3, 0xd7,
	0x75, 0xb8, 0x8d, 0xa3, 0xf6, 0xb8, 0x38, 0xa8, 0x80, 0xf6, 0xe4, 0xaa, 0x58, 0x5e, 0x8c, 0xe6,
	0x8b, 0xe2, 0x3a, 0xbf, 0xd8, 0xf6, 0xe9, 0xcb, 0xfb, 0x1d, 0x3c, 0xc5, 0x8f, 0xd6, 0x74, 0x79,
	0x30, 0xd9, 0x85, 0xce, 0xdf, 0x06, 0x1c, 0xbc, 0x45, 0xa0, 0xdf, 0x6f, 0x8b, 0xdf, 0xee, 0x3e,
	0x7d, 0xa0, 0xab, 0xeb, 0xf3, 0xed, 0xdb, 0x1b, 0x2f, 0xf2, 0xf1, 0xac, 0xda, 0xbe, 0xbd, 0x15,
	0x74, 0x7e, 0x83, 0x9a, 0xcf, 0xdf, 0xce, 0xe1, 0x00, 0x6c, 0x16, 0x45, 0x28, 0x06, 0xab, 0x20,
	0x2c, 0xa8, 0xb3, 0xb3, 0x98, 0xd4, 0x54, 0xf2, 0xec, 0x3c, 0x95, 0x48, 0xea, 0x94, 0xc0, 0xbe,
	0x17, 0x84, 0x29, 0xef, 0x87, 0xa9, 0xe0, 0xf2, 0x25, 0x31, 0xe9, 0x1e, 0x98, 0xdc, 0x0b, 0x63,
	0xd2, 0x50, 0x7c, 0xf4, 0x62, 0xd2, 0xd4, 0x95, 0xf0, 0x90, 0x58, 0xb4, 0x0d, 0x30, 0x4c, 0x7b,
	0x28, 0x05, 0x26, 0x18, 0x93, 0x3d, 0x55, 0x8b, 0x50, 0x32, 0x2f, 0x40, 0x62, 0x3f, 0xfd, 0xd3,
	0x80, 0xe6, 0xea, 0x2a, 0xef, 0xf4, 0x4e, 0x84, 0xc9, 0x28, 0x4e, 0x98, 0x4c, 0x90, 0x13, 0x43,
	0xfd, 0x2b, 0x53, 0x21, 0x7c, 0x31, 0x58, 0x35, 0x2f, 0x62, 0x69, 0x8c, 0x9c, 0xd4, 0xd5, 0xb8,
	0x71, 0x1a, 0x47, 0x28, 0x38, 0x72, 0x62, 0xae, 0xa0, 0xe7, 0x21, 0x2a, 0xd8, 0xa0, 0x1f, 0xc2,
	0x93, 0x3e, 0xf3, 0x03, 0xe4, 0x23, 0x2f, 0x14, 0x89, 0x2f, 0x52, 0x24, 0x4d, 0xd5, 0xb4, 0x04,
	0xe5, 0xa9, 0x2f, 0x58, 0x40, 0x2c, 0x85, 0x3c, 0x26, 0x3c, 0x0c, 0x90, 0x93, 0x3d, 0x85, 0x24,
	0x72, 0x5f, 0xa2, 0x97, 0x10, 0x5b, 0xed, 0x1a, 0x27, 0x61, 0x14, 0x21, 0x27, 0xa0, 0xc1, 0xd0,
	0xd7, 0xa0, 0xa5, 0x78, 0xbd, 0xb4, 0xdf, 0x47, 0x89, 0x9c, 0xec, 0xf7, 0x7e, 0x86, 0x2f, 0x26,
	0xc5, 0x6b, 0x77, 0x96, 0x55, 0xbf, 0x5c, 0xe5, 0x37, 0x3b, 0xd1, 0x5c, 0x16, 0x8b, 0xcb, 0xdd,
	0x7c, 0x22, 0xe3, 0xfc, 0xf9, 0x34, 0xaf, 0x7e, 0x5d, 0xbe, 0x72, 0x27, 0xc5, 0xeb, 0x93, 0x2d,
	0xf1, 0x44, 0x11, 0xf5, 0xe7, 0x2b, 0xcd, 0x3e, 0x59, 0x7d, 0xb5, 0xe6, 0x55, 0x53, 0x83, 0x6f,
	0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x99, 0x0b, 0x2d, 0xa6, 0x7f, 0x06, 0x00, 0x00,
}
